### ISSUE TITLE
Custom sound support

### ISSUE THREAD

**Issue by Keith94** [dimotsai/react-alarm-clock#1]
Can you add the ability to set a custom alarm sound? Maybe for local files or something else too. Thanks.

**Comment by dimotsai** [comment]
Yes, it should be possible through File API. Or maybe a hyperlink of a custom sound

**Comment by Keith94** [comment]
Thanks for adding it!

Local files work but supports only mp3 types (FLAC not supported)?

I tested some audio URLs, but I don't think they are working. For example this one doesn't play: http://shule-aroon.sakura.ne.jp/hanauta/02_sample.mp3

**Comment by dimotsai** [comment]
@Keith94 I am not sure what browser you are using. But according to [this article](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats), it seems that only Firefox (>=51) support FLAC.

I haven't tried audio URL on other browsers, but mine works fine with your link on Chromium.

**Comment by dimotsai** [comment]
Custom audio URLs should be working on Firefox now.

**Comment by Keith94** [comment]
Yes, I'm using Firefox 53 (currently in Nightly branch) which supports FLAC playback. Can it be supported here too?

>Custom audio URLs should be working on Firefox now.

Now it works for me. :)

**Comment by dimotsai** [comment]
I have already added FLAC support, could you test it for me?
This file works on my Firefox Nightly 53.0a1: http://www.lindberg.no/hires/test/2L-125_stereo-44k-16b_04.flac

**Comment by Keith94** [comment]
My bad, it does already work for audio URLs, however when I add a local .flac file, it says "unsupported audio type".

**Comment by dimotsai** [comment]
@Keith94 Commit c422ed2efea3130598065b437ccf597e79ab02e9 should fix that.
